// <auto-generated />
namespace CompanyManager.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class PersonDBv4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonDBv4));
        
        string IMigrationMetadata.Id
        {
            get { return "202005041904495_PersonDB-v4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
